# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqYEWkM5X27VQwqG8s0FgZ1WkYxpj2OX
"""

import pandas as pd
baza={
    "FISH":["Aliyev Vali","Valiyev Ali ", "Teshayev Bolta","Boltayev Tesha","Sobirova Mohinur"  ],
    "Yoshi":[ "19","17","15","20","21"  ],
    "Maktabi":[ "20-maktab","25-maktab","34-maktab","45-maktab","35-maktab" ],
    "Jinsi":[ "o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","qiz bola"],
    "Manzili":[ "Farg'ona viloyati","Toshkent viloyati","Buxoro viloyati","Samarqand viloyati","Farg'ona shahar"],
}
db=pd.DataFrame(baza)
print(db)

Filtr=db[db['Maktabi']=='35-maktab']
print(Filtr)

Filtr=db[(db['Maktabi']=='35-maktab')    &   ( db['Maktabi']=='35-maktab')]
print(Filtr)